// QUESTO FILE CONTIENE SOLO I DATI DEGLI EVENTI.
// Per aggiungere un evento: copia un blocco { ... }, incollalo prima della riga ];
// e cambia i valori. Ricordati la virgola dopo la parentesi graffa } di chiusura.
//
// Campi di ogni evento:
//   id          -> numero unico, mai usato prima
//   titolo      -> nome dell'evento
//   data        -> quando è successo (testo leggibile, es. "15 marzo 44 a.C.")
//   anno        -> lo stesso anno ma come NUMERO, per i filtri della timeline.
//                  Anni dopo Cristo: numero positivo (es. 1848).
//                  Anni avanti Cristo: numero negativo (es. 44 a.C. -> -44).
//                  Se l'evento dura più anni, usa l'anno di inizio.
//   luogo       -> dove è successo
//   categoria   -> una di: "Roma antica", "Medioevo", "Rinascimento",
//                  "Età moderna", "Risorgimento", "Novecento"
//   lat, lon    -> coordinate GPS (numeri col punto, es. 41.8902)
//   descrizione -> una o due frasi; se c'è un apostrofo usa le virgolette doppie "..."
//   fonte       -> link a una pagina di Wikipedia (per il "Fonte" nel dettaglio)
//   curiosita   -> (facoltativo) un "Lo sapevi che...?" legato all'evento; se manca, non appare
//   immagine    -> (facoltativo) URL di un'immagine da Wikimedia Commons; se manca, la scheda
//                  non mostra immagine. Aggiungerne una solo se è davvero pertinente e reale
//                  (mai inventare un URL): prendila dall'immagine principale della pagina
//                  Wikipedia già indicata in "fonte".

const eventi = [
  {
    id: 1,
    titolo: 'Inaugurazione del Colosseo',
    data: '25 maggio 80 d.C.',
    anno: 80,
    luogo: 'Colosseo, Roma',
    categoria: 'Roma antica',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Colosseo_2020.jpg/330px-Colosseo_2020.jpg',
    lat: 41.8902,
    lon: 12.4922,
    descrizione: "L'imperatore Tito inaugura solennemente l'Anfiteatro Flavio dopo 8 anni di costruzione.",
    fonte: 'https://it.wikipedia.org/wiki/Colosseo',
    curiosita: "Il Colosseo aveva 80 ingressi numerati che permettevano di svuotarlo in pochi minuti: gli stessi 'vomitoria' che ancora oggi ispirano gli stadi moderni."
  },
  {
    id: 2,
    titolo: 'Assassinio di Giulio Cesare',
    data: '15 marzo 44 a.C.',
    anno: -44,
    luogo: 'Curia di Pompeo, Roma',
    categoria: 'Roma antica',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Vincenzo_Camuccini_-_La_morte_di_Cesare.jpg/330px-Vincenzo_Camuccini_-_La_morte_di_Cesare.jpg',
    lat: 41.8956,
    lon: 12.4769,
    descrizione: 'Giulio Cesare viene assassinato da un gruppo di senatori durante la seduta del Senato.',
    fonte: 'https://it.wikipedia.org/wiki/Cesaricidio',
    curiosita: "Gli storici antichi non concordano sulle ultime parole di Cesare: la celebre 'Tu quoque, Brute?' deve la sua fama soprattutto a Shakespeare."
  },
  {
    id: 3,
    titolo: 'Ultima Cena di Leonardo',
    data: '1495-1498',
    anno: 1495,
    luogo: 'Santa Maria delle Grazie, Milano',
    categoria: 'Rinascimento',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Leonardo_da_Vinci_-_The_Last_Supper_high_res.jpg/330px-Leonardo_da_Vinci_-_The_Last_Supper_high_res.jpg',
    lat: 45.4659,
    lon: 9.1706,
    descrizione: 'Leonardo da Vinci dipinge il Cenacolo nel refettorio del convento domenicano.',
    fonte: 'https://it.wikipedia.org/wiki/Ultima_Cena_(Leonardo)',
    curiosita: "Leonardo dipinse a secco invece che ad affresco: per questo l'opera iniziò a rovinarsi già mentre lui era ancora in vita."
  },
  {
    id: 4,
    titolo: 'Le Cinque Giornate di Milano',
    data: '18-22 marzo 1848',
    anno: 1848,
    luogo: 'Centro storico, Milano',
    categoria: 'Risorgimento',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Episodio_delle_cinque_giornate_%28Baldassare_Verazzi%29.jpg/250px-Episodio_delle_cinque_giornate_%28Baldassare_Verazzi%29.jpg',
    lat: 45.4642,
    lon: 9.1900,
    descrizione: 'I milanesi insorgono contro il dominio austriaco e cacciano le truppe di Radetzky dalla città.',
    fonte: 'https://it.wikipedia.org/wiki/Cinque_giornate_di_Milano',
    curiosita: "In pochi giorni i milanesi eressero oltre 1600 barricate, usando mobili, carrozze rovesciate e persino i banchi delle chiese."
  },
  {
    id: 5,
    titolo: 'Editto di Milano',
    data: '313 d.C.',
    anno: 313,
    luogo: 'Palazzo Imperiale, Milano (Mediolanum)',
    categoria: 'Roma antica',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/IMG_6735_-_Milano_-_S._Giorgio_al_Palazzo_-_Lapide_1978_x_Editto_di_Milano_-313-._-_Foto_Giovanni_Dall%27Orto_-_8-Mar-2007.jpg/330px-IMG_6735_-_Milano_-_S._Giorgio_al_Palazzo_-_Lapide_1978_x_Editto_di_Milano_-313-._-_Foto_Giovanni_Dall%27Orto_-_8-Mar-2007.jpg',
    lat: 45.4638,
    lon: 9.1781,
    descrizione: "Gli imperatori Costantino e Licinio concedono libertà di culto ai cristiani in tutto l'Impero romano.",
    fonte: 'https://it.wikipedia.org/wiki/Editto_di_Milano',
    curiosita: "Non fu un vero editto scritto a Milano: fu un accordo tra Costantino e Licinio, poi diffuso con lettere ai governatori delle province."
  },
  {
    id: 6,
    titolo: 'Congiura dei Pazzi',
    data: '26 aprile 1478',
    anno: 1478,
    luogo: 'Cattedrale di Santa Maria del Fiore, Firenze',
    categoria: 'Rinascimento',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Bertoldo_di_giovanni%2C_medaglia_della_congiura_dei_pazzi%2C_1478.JPG/330px-Bertoldo_di_giovanni%2C_medaglia_della_congiura_dei_pazzi%2C_1478.JPG',
    lat: 43.7731,
    lon: 11.2560,
    descrizione: "Durante la messa nel Duomo, Giuliano de' Medici viene assassinato; il fratello Lorenzo il Magnifico resta ferito ma si salva.",
    fonte: 'https://it.wikipedia.org/wiki/Congiura_dei_Pazzi',
    curiosita: "Botticelli fu incaricato di dipingere i congiurati impiccati sulla facciata del palazzo del Bargello, come monito pubblico."
  },
  {
    id: 7,
    titolo: 'Rogo di Girolamo Savonarola',
    data: '23 maggio 1498',
    anno: 1498,
    luogo: 'Piazza della Signoria, Firenze',
    categoria: 'Rinascimento',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Girolamo_Savonarola_by_Fra_Bartolommeo_%281497%29.jpg/250px-Girolamo_Savonarola_by_Fra_Bartolommeo_%281497%29.jpg',
    lat: 43.7696,
    lon: 11.2558,
    descrizione: 'Il frate domenicano Savonarola viene impiccato e bruciato in piazza insieme a due confratelli, dopo la condanna per eresia.',
    fonte: 'https://it.wikipedia.org/wiki/Girolamo_Savonarola',
    curiosita: "Nel punto esatto del rogo una lapide rotonda, incassata nel selciato di Piazza della Signoria, lo ricorda ancora oggi."
  },
  {
    id: 8,
    titolo: 'Rivolta di Masaniello',
    data: '7 luglio 1647',
    anno: 1647,
    luogo: 'Piazza Mercato, Napoli',
    categoria: 'Età moderna',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Masaniello.jpg/330px-Masaniello.jpg',
    lat: 40.8478,
    lon: 14.2665,
    descrizione: "Il pescatore Masaniello guida la rivolta popolare napoletana contro le tasse imposte dal governo spagnolo.",
    fonte: 'https://it.wikipedia.org/wiki/Masaniello',
    curiosita: "Masaniello guidò Napoli per appena dieci giorni: fu ucciso da alcuni suoi ex sostenitori, ma il giorno dopo la folla lo pianse come un eroe."
  },
  {
    id: 9,
    titolo: 'Eruzione del Vesuvio',
    data: '79 d.C.',
    anno: 79,
    luogo: 'Pompei',
    categoria: 'Roma antica',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Pompei%2C_il_Vesuvio_da_via_delle_Scuole_-_panoramio.jpg/330px-Pompei%2C_il_Vesuvio_da_via_delle_Scuole_-_panoramio.jpg',
    lat: 40.7491,
    lon: 14.4869,
    descrizione: "L'eruzione del Vesuvio seppellisce sotto cenere e lapilli le città di Pompei, Ercolano e Stabia.",
    fonte: 'https://it.wikipedia.org/wiki/Eruzione_del_Vesuvio_del_79',
    curiosita: "I celebri calchi delle vittime sono cavità lasciate dai corpi nella cenere indurita: gli archeologi dell'Ottocento le riempirono di gesso."
  },
  {
    id: 10,
    titolo: 'Inizio della costruzione della Torre di Pisa',
    data: '1173',
    anno: 1173,
    luogo: 'Piazza dei Miracoli, Pisa',
    categoria: 'Medioevo',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/The_Leaning_Tower_of_Pisa_2026.jpg/250px-The_Leaning_Tower_of_Pisa_2026.jpg',
    lat: 43.7230,
    lon: 10.3966,
    descrizione: 'Iniziano i lavori del campanile del Duomo; la torre comincia a pendere già durante la costruzione per il cedimento del terreno.',
    fonte: 'https://it.wikipedia.org/wiki/Torre_di_Pisa',
    curiosita: "I lavori furono interrotti per quasi un secolo a causa delle guerre: quella lunga pausa fece assestare il terreno e probabilmente salvò la torre dal crollo."
  },
  {
    id: 11,
    titolo: "Fondazione dell'Università di Bologna",
    data: '1088',
    anno: 1088,
    luogo: 'Bologna',
    categoria: 'Medioevo',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Palazzo_Poggi_UniBo.jpg/250px-Palazzo_Poggi_UniBo.jpg',
    lat: 44.4949,
    lon: 11.3426,
    descrizione: "Nasce lo Studium di Bologna, considerato la più antica università del mondo occidentale ancora in attività.",
    fonte: "https://it.wikipedia.org/wiki/Università_di_Bologna",
    curiosita: "Il suo motto è 'Alma Mater Studiorum': da qui viene l'espressione 'alma mater' usata in tutto il mondo per indicare la propria università."
  },
  {
    id: 12,
    titolo: 'Vespri siciliani',
    data: '31 marzo 1282',
    anno: 1282,
    luogo: 'Chiesa di Santo Spirito, Palermo',
    categoria: 'Medioevo',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Francesco_Hayez_023.jpg/330px-Francesco_Hayez_023.jpg',
    lat: 38.0940,
    lon: 13.3772,
    descrizione: "All'ora dei vespri scoppia a Palermo la rivolta contro il dominio angioino francese, che si estende a tutta la Sicilia.",
    fonte: 'https://it.wikipedia.org/wiki/Vespri_siciliani',
    curiosita: "Secondo la tradizione la scintilla fu un soldato francese che importunò una giovane sposa davanti alla chiesa, proprio all'ora dei vespri."
  },
  {
    id: 13,
    titolo: "Proclamazione del Regno d'Italia",
    data: '17 marzo 1861',
    anno: 1861,
    luogo: 'Palazzo Carignano, Torino',
    categoria: 'Risorgimento',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Proclamazione_del_Regno_d%27Italia.png/330px-Proclamazione_del_Regno_d%27Italia.png',
    lat: 45.0672,
    lon: 7.6858,
    descrizione: "Il primo Parlamento italiano, riunito a Torino, proclama Vittorio Emanuele II re d'Italia.",
    fonte: "https://it.wikipedia.org/wiki/Proclamazione_del_Regno_d'Italia",
    curiosita: "Vittorio Emanuele II mantenne il numero 'II' invece di diventare 'I d'Italia': una scelta che molti patrioti criticarono come un'occasione persa."
  },
  {
    id: 14,
    titolo: 'Breccia di Porta Pia',
    data: '20 settembre 1870',
    anno: 1870,
    luogo: 'Porta Pia, Roma',
    categoria: 'Risorgimento',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/BrecciaPortaPia.jpg/330px-BrecciaPortaPia.jpg',
    lat: 41.9110,
    lon: 12.5040,
    descrizione: "I bersaglieri entrano a Roma attraverso una breccia presso Porta Pia: finisce lo Stato Pontificio e Roma diventa capitale d'Italia.",
    fonte: 'https://it.wikipedia.org/wiki/Presa_di_Roma',
    curiosita: "Roma divenne davvero capitale solo nel 1871: prima lo erano state Torino e poi Firenze, che dovette 'restituire' il ruolo dopo pochi anni."
  },
  {
    id: 15,
    titolo: 'Battaglia di Magenta',
    data: '4 giugno 1859',
    anno: 1859,
    luogo: 'Magenta, Milano',
    categoria: 'Risorgimento',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Bataille_de_Magenta.jpg/330px-Bataille_de_Magenta.jpg',
    lat: 45.46282,
    lon: 8.87702,
    descrizione: "L'esercito franco-piemontese, guidato da Napoleone III, sconfigge l'esercito imperiale austriaco, aprendo la strada verso Milano.",
    fonte: 'https://it.wikipedia.org/wiki/Battaglia_di_Magenta',
    curiosita: "Il colore 'magenta', un rosso-violaceo appena inventato in quegli anni, prese il nome proprio da questa battaglia."
  },
  {
    id: 16,
    titolo: 'Battaglia di Legnano',
    data: '29 maggio 1176',
    anno: 1176,
    luogo: 'Legnano, Milano',
    categoria: 'Medioevo',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/La_battaglia_di_Legnano_di_Amos_Cassoli.jpg/330px-La_battaglia_di_Legnano_di_Amos_Cassoli.jpg',
    lat: 45.5931,
    lon: 8.9186,
    descrizione: "I Comuni della Lega Lombarda sconfiggono l'esercito dell'imperatore Federico Barbarossa, difendendo la loro autonomia.",
    fonte: 'https://it.wikipedia.org/wiki/Battaglia_di_Legnano',
    curiosita: "'Dovunque è Legnano', recita l'inno di Mameli: è l'unica battaglia citata nell'inno nazionale italiano."
  },
  {
    id: 17,
    titolo: 'Editto di Rotari',
    data: '22 novembre 643',
    anno: 643,
    luogo: 'Pavia',
    categoria: 'Medioevo',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/RO005.jpg/250px-RO005.jpg',
    lat: 45.1847,
    lon: 9.1582,
    descrizione: "Il re longobardo Rotari promulga a Pavia la prima raccolta scritta delle leggi del suo popolo, in lingua latina.",
    fonte: 'https://it.wikipedia.org/wiki/Editto_di_Rotari',
    curiosita: "Fu scritto in latino, non in lingua longobarda: i Longobardi non usavano una propria scrittura per le leggi."
  },
  {
    id: 18,
    titolo: 'Incoronazione di Carlo Magno',
    data: '25 dicembre 800',
    anno: 800,
    luogo: 'Basilica di San Pietro, Roma',
    categoria: 'Medioevo',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Dürer_karl_der_grosse.jpg/250px-Dürer_karl_der_grosse.jpg',
    lat: 41.9022,
    lon: 12.4539,
    descrizione: "Papa Leone III incorona Carlo Magno imperatore dei Romani durante la messa di Natale, dando vita al Sacro Romano Impero.",
    fonte: 'https://it.wikipedia.org/wiki/Carlo_Magno',
    curiosita: "Il suo biografo Eginardo racconta che Carlo Magno disse che non sarebbe entrato in chiesa se avesse saputo delle intenzioni del papa."
  },
  {
    id: 19,
    titolo: 'Fondazione leggendaria di Venezia',
    data: '25 marzo 421',
    anno: 421,
    luogo: 'Rialto, Venezia',
    categoria: 'Roma antica',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Canaletto_-_The_Entrance_to_the_Grand_Canal%2C_Venice_-_Google_Art_Project.jpg/330px-Canaletto_-_The_Entrance_to_the_Grand_Canal%2C_Venice_-_Google_Art_Project.jpg',
    lat: 45.4380,
    lon: 12.3358,
    descrizione: "La tradizione fissa in questa data la nascita di Venezia, con la dedicazione della chiesa di San Giacomo di Rialto.",
    fonte: 'https://it.wikipedia.org/wiki/Storia_di_Venezia',
    curiosita: "La data è simbolica: Venezia nacque in realtà nel corso di secoli, mentre gli abitanti della terraferma si rifugiavano in laguna dalle invasioni."
  },
  {
    id: 20,
    titolo: 'Rogo di Giordano Bruno',
    data: '17 febbraio 1600',
    anno: 1600,
    luogo: "Campo de' Fiori, Roma",
    categoria: 'Età moderna',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Giordano_Bruno.jpg/250px-Giordano_Bruno.jpg',
    lat: 41.8955,
    lon: 12.4722,
    descrizione: "Il filosofo Giordano Bruno viene arso vivo per eresia; nel 1889 gli viene dedicata la statua che ancora domina la piazza.",
    fonte: 'https://it.wikipedia.org/wiki/Giordano_Bruno',
    curiosita: "La statua in Campo de' Fiori è rivolta di proposito verso il Vaticano; fu inaugurata nel 1889 tra le proteste della Chiesa."
  },
  {
    id: 21,
    titolo: 'Disfida di Barletta',
    data: '13 febbraio 1503',
    anno: 1503,
    luogo: 'Barletta',
    categoria: 'Rinascimento',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Cantina_della_Sfida.jpg/330px-Cantina_della_Sfida.jpg',
    lat: 41.3193,
    lon: 16.2820,
    descrizione: "Tredici cavalieri italiani guidati da Ettore Fieramosca sconfiggono in duello altrettanti cavalieri francesi.",
    fonte: 'https://it.wikipedia.org/wiki/Disfida_di_Barletta',
    curiosita: "L'episodio ispirò a Massimo d'Azeglio il romanzo 'Ettore Fieramosca' (1833), uno dei libri simbolo del Risorgimento."
  },
  {
    id: 22,
    titolo: 'Sacco di Roma',
    data: '6 maggio 1527',
    anno: 1527,
    luogo: "Castel Sant'Angelo, Roma",
    categoria: 'Rinascimento',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Sack_of_Rome_of_1527_by_Johannes_Lingelbach_17th_century.jpg/330px-Sack_of_Rome_of_1527_by_Johannes_Lingelbach_17th_century.jpg',
    lat: 41.9031,
    lon: 12.4663,
    descrizione: "Le truppe imperiali di Carlo V, in gran parte lanzichenecchi, saccheggiano Roma per mesi; papa Clemente VII si rifugia in Castel Sant'Angelo.",
    fonte: 'https://it.wikipedia.org/wiki/Sacco_di_Roma_(1527)',
    curiosita: "Quel giorno morirono 147 Guardie Svizzere su 189 per proteggere il papa: da allora le nuove reclute giurano proprio il 6 maggio."
  },
  {
    id: 23,
    titolo: 'Battaglia di Pavia',
    data: '24 febbraio 1525',
    anno: 1525,
    luogo: 'Parco Visconteo, Pavia',
    categoria: 'Rinascimento',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Battle_of_Pavia.jpg/330px-Battle_of_Pavia.jpg',
    lat: 45.2028,
    lon: 9.1503,
    descrizione: "L'esercito di Carlo V sconfigge i francesi e cattura il re Francesco I, che scrive: \"Tutto è perduto fuorché l'onore\".",
    fonte: 'https://it.wikipedia.org/wiki/Battaglia_di_Pavia_(1525)',
    curiosita: "Per liberare Francesco I, portato prigioniero in Spagna, servì un trattato e la consegna dei suoi due figli come ostaggi."
  },
  {
    id: 24,
    titolo: 'Concilio di Trento',
    data: '1545-1563',
    anno: 1545,
    luogo: 'Cattedrale di San Vigilio, Trento',
    categoria: 'Rinascimento',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Sebastiano_Ricci_034.jpg/330px-Sebastiano_Ricci_034.jpg',
    lat: 46.0679,
    lon: 11.1211,
    descrizione: "Il concilio che avvia la Controriforma cattolica si riunisce a più riprese a Trento per quasi vent'anni.",
    fonte: 'https://it.wikipedia.org/wiki/Concilio_di_Trento',
    curiosita: "Durò 18 anni ma si riunì davvero solo per circa quattro: fu più volte sospeso per pesti, guerre e liti tra papa e imperatore."
  },
  {
    id: 25,
    titolo: 'Abiura di Galileo Galilei',
    data: '22 giugno 1633',
    anno: 1633,
    luogo: 'Convento di Santa Maria sopra Minerva, Roma',
    categoria: 'Età moderna',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Galileo_before_the_Holy_Office_-_Joseph-Nicolas_Robert-Fleury%2C_1847.png/330px-Galileo_before_the_Holy_Office_-_Joseph-Nicolas_Robert-Fleury%2C_1847.png',
    lat: 41.8983,
    lon: 12.4779,
    descrizione: "Processato dall'Inquisizione per aver sostenuto che la Terra gira intorno al Sole, Galileo è costretto ad abiurare le sue idee.",
    fonte: 'https://it.wikipedia.org/wiki/Processo_a_Galileo_Galilei',
    curiosita: "La Chiesa cattolica riconobbe ufficialmente l'errore di quel processo solo nel 1992, con una commissione voluta da Giovanni Paolo II."
  },
  {
    id: 26,
    titolo: "Incoronazione di Napoleone a re d'Italia",
    data: '26 maggio 1805',
    anno: 1805,
    luogo: 'Duomo di Milano',
    categoria: 'Età moderna',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Napoleon_I_of_France_by_Andrea_Appiani.jpg/250px-Napoleon_I_of_France_by_Andrea_Appiani.jpg',
    lat: 45.4641,
    lon: 9.1919,
    descrizione: "Napoleone Bonaparte si cinge il capo con la Corona Ferrea dicendo: \"Dio me l'ha data, guai a chi la tocca\".",
    fonte: "https://it.wikipedia.org/wiki/Regno_d'Italia_(1805-1814)",
    curiosita: "La Corona Ferrea prende il nome da un sottile cerchio di ferro all'interno, che secondo la tradizione fu ricavato da un chiodo della croce di Cristo."
  },
  {
    id: 27,
    titolo: 'Partenza dei Mille da Quarto',
    data: '5 maggio 1860',
    anno: 1860,
    luogo: 'Quarto, Genova',
    categoria: 'Risorgimento',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Partenza_da_Quarto.jpg/330px-Partenza_da_Quarto.jpg',
    lat: 44.3866,
    lon: 9.0353,
    descrizione: "Giuseppe Garibaldi salpa con circa mille volontari su due piroscafi per liberare il Regno delle Due Sicilie.",
    fonte: 'https://it.wikipedia.org/wiki/Spedizione_dei_Mille',
    curiosita: "I due piroscafi, il Piemonte e il Lombardo, furono presi 'in prestito' alla compagnia Rubattino di Genova con la complicità dei suoi dirigenti."
  },
  {
    id: 28,
    titolo: 'Sbarco dei Mille a Marsala',
    data: '11 maggio 1860',
    anno: 1860,
    luogo: 'Marsala',
    categoria: 'Risorgimento',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Garibaldi_a_Marsala_%28Gerolamo_Induno%2C_Italy%2C_1861%29.png/330px-Garibaldi_a_Marsala_%28Gerolamo_Induno%2C_Italy%2C_1861%29.png',
    lat: 37.7986,
    lon: 12.4360,
    descrizione: "I Mille di Garibaldi sbarcano in Sicilia dando inizio alla spedizione che porterà alla caduta dei Borbone.",
    fonte: 'https://it.wikipedia.org/wiki/Spedizione_dei_Mille',
    curiosita: "Due navi da guerra britanniche erano ormeggiate nel porto: la marina borbonica esitò a sparare e i Mille sbarcarono quasi indisturbati."
  },
  {
    id: 29,
    titolo: 'Battaglia di Solferino e San Martino',
    data: '24 giugno 1859',
    anno: 1859,
    luogo: 'Solferino, Mantova',
    categoria: 'Risorgimento',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Napol%C3%A9on_III_%C3%A0_la_bataille_de_Solf%C3%A9rino..jpg/330px-Napol%C3%A9on_III_%C3%A0_la_bataille_de_Solf%C3%A9rino..jpg',
    lat: 45.3719,
    lon: 10.5686,
    descrizione: "Franco-piemontesi e austriaci si scontrano in una battaglia sanguinosissima; il ricordo dei feriti abbandonati ispira a Henry Dunant la Croce Rossa.",
    fonte: 'https://it.wikipedia.org/wiki/Battaglia_di_Solferino_e_San_Martino',
    curiosita: "Lo svizzero Henry Dunant, sconvolto dalle migliaia di feriti lasciati senza cure, scrisse un libro che portò alla nascita della Croce Rossa."
  },
  {
    id: 30,
    titolo: 'Incontro di Teano',
    data: '26 ottobre 1860',
    anno: 1860,
    luogo: 'Teano, Caserta',
    categoria: 'Risorgimento',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Historic_meeting_at_Teano_between_Victor_Emmanuel_and_Garibaldi.jpg/250px-Historic_meeting_at_Teano_between_Victor_Emmanuel_and_Garibaldi.jpg',
    lat: 41.2497,
    lon: 14.0653,
    descrizione: "Garibaldi consegna a Vittorio Emanuele II le terre conquistate nel Sud, salutandolo come re d'Italia.",
    fonte: 'https://it.wikipedia.org/wiki/Incontro_di_Teano',
    curiosita: "Il luogo esatto dell'incontro è ancora discusso: alcuni storici lo collocano non a Teano ma nella vicina Vairano Patenora."
  },
  {
    id: 31,
    titolo: 'Terremoto di Messina',
    data: '28 dicembre 1908',
    anno: 1908,
    luogo: 'Messina',
    categoria: 'Novecento',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Terremoto_del_1908_-_Antica_cartolina_con_l%27indicazione_di_Reggio_e_di_Messina.jpg/330px-Terremoto_del_1908_-_Antica_cartolina_con_l%27indicazione_di_Reggio_e_di_Messina.jpg',
    lat: 38.1938,
    lon: 15.5540,
    descrizione: "Un terremoto seguito da un maremoto distrugge Messina e Reggio Calabria, causando decine di migliaia di vittime.",
    fonte: 'https://it.wikipedia.org/wiki/Terremoto_di_Messina_del_1908',
    curiosita: "Fu uno dei primi disastri soccorsi via mare da più nazioni: navi russe, britanniche e statunitensi arrivarono già nei giorni successivi."
  },
  {
    id: 32,
    titolo: 'Battaglia di Vittorio Veneto',
    data: '24 ottobre - 3 novembre 1918',
    anno: 1918,
    luogo: 'Vittorio Veneto, Treviso',
    categoria: 'Novecento',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Trento_3_novembre_1918.jpg/330px-Trento_3_novembre_1918.jpg',
    lat: 45.9950,
    lon: 12.3000,
    descrizione: "L'offensiva finale dell'esercito italiano sfonda il fronte austro-ungarico e porta all'armistizio del 4 novembre 1918.",
    fonte: 'https://it.wikipedia.org/wiki/Battaglia_di_Vittorio_Veneto',
    curiosita: "Il 4 novembre, data della vittoria, è ancora oggi festa nazionale: la Giornata dell'Unità Nazionale e delle Forze Armate."
  },
  {
    id: 33,
    titolo: 'Nascita della Repubblica Italiana',
    data: '2 giugno 1946',
    anno: 1946,
    luogo: 'Roma',
    categoria: 'Novecento',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Corriere_della_sera_-_6_giugno_1946_-_%C3%88_nata_la_Repubblica_italiana.pdf/page1-330px-Corriere_della_sera_-_6_giugno_1946_-_%C3%88_nata_la_Repubblica_italiana.pdf.jpg',
    lat: 41.9000,
    lon: 12.4790,
    descrizione: "Con un referendum gli italiani, per la prima volta anche le donne, scelgono la repubblica al posto della monarchia.",
    fonte: 'https://it.wikipedia.org/wiki/Nascita_della_Repubblica_Italiana',
    curiosita: "Fu il primo voto nazionale delle donne italiane: erano state ammesse al voto solo pochi mesi prima, nelle elezioni comunali del marzo 1946."
  },
  {
    id: 34,
    titolo: 'Alluvione di Firenze',
    data: '4 novembre 1966',
    anno: 1966,
    luogo: 'Firenze',
    categoria: 'Novecento',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/1966_Arno_Florence_flood_2008.JPG/330px-1966_Arno_Florence_flood_2008.JPG',
    lat: 43.7700,
    lon: 11.2560,
    descrizione: "L'Arno straripa e sommerge la città; da tutto il mondo arrivano volontari, gli \"angeli del fango\", per salvare libri e opere d'arte.",
    fonte: 'https://it.wikipedia.org/wiki/Alluvione_di_Firenze_del_4_novembre_1966',
    curiosita: "Gli 'angeli del fango' arrivarono da tutta Europa, spesso giovanissimi, e lavorarono per settimane nelle cantine e negli archivi allagati."
  },
  {
    id: 35,
    titolo: 'Disastro del Vajont',
    data: '9 ottobre 1963',
    anno: 1963,
    luogo: 'Diga del Vajont, Longarone',
    categoria: 'Novecento',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Vajont1963_5.jpg/330px-Vajont1963_5.jpg',
    lat: 46.2673,
    lon: 12.3289,
    descrizione: "Una frana dal monte Toc precipita nel bacino artificiale: l'ondata scavalca la diga e distrugge Longarone e i paesi vicini.",
    fonte: 'https://it.wikipedia.org/wiki/Disastro_del_Vajont',
    curiosita: "La diga è ancora in piedi e intatta: la tragedia non fu causata da un suo cedimento, ma dall'onda che la scavalcò dopo la frana."
  },
  {
    id: 36,
    titolo: 'Fondazione di Roma',
    data: '21 aprile 753 a.C. (tradizionale)',
    anno: -753,
    luogo: 'Palatino, Roma',
    categoria: 'Roma antica',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Lupa_Capitolina%2C_Rome.jpg/330px-Lupa_Capitolina%2C_Rome.jpg',
    lat: 41.8925,
    lon: 12.4853,
    descrizione: 'Secondo la tradizione romana, Romolo fonda Roma sul colle Palatino, tracciandone il perimetro sacro con un aratro.',
    fonte: 'https://it.wikipedia.org/wiki/Fondazione_di_Roma',
    curiosita: "La data del 21 aprile 753 a.C. non viene da documenti dell'epoca: fu calcolata secoli dopo dall'erudito latino Varrone."
  },
  {
    id: 37,
    titolo: 'Battaglia del Trasimeno',
    data: '21 giugno 217 a.C.',
    anno: -217,
    luogo: 'Lago Trasimeno, Tuoro sul Trasimeno',
    categoria: 'Roma antica',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Trasimene_battlefield.JPG/330px-Trasimene_battlefield.JPG',
    lat: 43.1833,
    lon: 12.1167,
    descrizione: "Annibale tende un'imboscata all'esercito romano lungo le rive del lago Trasimeno, infliggendo una delle sconfitte più gravi della storia di Roma.",
    fonte: 'https://it.wikipedia.org/wiki/Battaglia_del_Trasimeno'
  },
  {
    id: 38,
    titolo: "Ravenna diventa capitale dell'Impero romano d'Occidente",
    data: '402 d.C.',
    anno: 402,
    luogo: 'Ravenna',
    categoria: 'Roma antica',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Early_Christian_Monuments_of_Ravenna.jpg/250px-Early_Christian_Monuments_of_Ravenna.jpg',
    lat: 44.4184,
    lon: 12.2035,
    descrizione: "L'imperatore Onorio trasferisce da Milano a Ravenna la capitale dell'Impero romano d'Occidente.",
    fonte: 'https://it.wikipedia.org/wiki/Ravenna',
    curiosita: 'Onorio scelse Ravenna, protetta da paludi difficili da attraversare, per sfuggire alle minacce del re visigoto Alarico.'
  },
  {
    id: 39,
    titolo: 'Martiri di Otranto',
    data: '11 agosto 1480',
    anno: 1480,
    luogo: 'Otranto',
    categoria: 'Medioevo',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/M%C3%A1rtires_de_Otranto.jpg/250px-M%C3%A1rtires_de_Otranto.jpg',
    lat: 40.1460,
    lon: 18.4880,
    descrizione: "Dopo un assedio di quindici giorni, le truppe ottomane conquistano Otranto: centinaia di abitanti vengono uccisi per essersi rifiutati di rinnegare la fede cristiana.",
    fonte: 'https://it.wikipedia.org/wiki/Martiri_di_Otranto',
    curiosita: "L'assedio era durato solo quindici giorni: la città cadde il giorno dopo l'attacco finale ordinato dal comandante ottomano Gedik Ahmet Pascià."
  },
  {
    id: 40,
    titolo: 'Battaglia di Benevento',
    data: '26 febbraio 1266',
    anno: 1266,
    luogo: 'Benevento',
    categoria: 'Medioevo',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Villani_Benevento.jpg/330px-Villani_Benevento.jpg',
    lat: 41.1298,
    lon: 14.7826,
    descrizione: 'Nella battaglia di Benevento le truppe guelfe di Carlo I d\'Angiò sconfiggono quelle ghibelline di Manfredi di Sicilia, che muore in combattimento.',
    fonte: 'https://it.wikipedia.org/wiki/Battaglia_di_Benevento_(1266)'
  },
  {
    id: 41,
    titolo: "Posa della prima pietra della Basilica di San Francesco d'Assisi",
    data: '16 luglio 1228',
    anno: 1228,
    luogo: 'Assisi',
    categoria: 'Medioevo',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Basilica_san_Francesco_di_Assisi.jpg/330px-Basilica_san_Francesco_di_Assisi.jpg',
    lat: 43.0707,
    lon: 12.6055,
    descrizione: 'Il giorno dopo la canonizzazione di san Francesco, viene posata ad Assisi la prima pietra della basilica a lui dedicata.',
    fonte: "https://it.wikipedia.org/wiki/Basilica_di_San_Francesco_d'Assisi",
    curiosita: 'La prima pietra fu posata appena un giorno dopo la canonizzazione, il 15 luglio 1228, da papa Gregorio IX e da frate Elia da Cortona.'
  },
  {
    id: 42,
    titolo: 'Pace di Lodi',
    data: '9 aprile 1454',
    anno: 1454,
    luogo: 'Lodi',
    categoria: 'Rinascimento',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Map_Italy_in_1454-_Touring_Club_Italiano_CART-TRC-46.jpg/330px-Map_Italy_in_1454-_Touring_Club_Italiano_CART-TRC-46.jpg',
    lat: 45.3142,
    lon: 9.5034,
    descrizione: 'Milano, Venezia, Firenze, Napoli e lo Stato Pontificio firmano a Lodi una pace che stabilizza a lungo gli equilibri tra gli stati italiani.',
    fonte: 'https://it.wikipedia.org/wiki/Pace_di_Lodi'
  },
  {
    id: 43,
    titolo: 'Inizio degli affreschi della volta della Cappella Sistina',
    data: '1508-1512',
    anno: 1508,
    luogo: 'Cappella Sistina, Città del Vaticano',
    categoria: 'Rinascimento',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Cappella_sistina%2C_volta_00.jpg/250px-Cappella_sistina%2C_volta_00.jpg',
    lat: 41.9029,
    lon: 12.4545,
    descrizione: 'Michelangelo inizia a dipingere la volta della Cappella Sistina in Vaticano, portandola a termine quattro anni più tardi.',
    fonte: 'https://it.wikipedia.org/wiki/Volta_della_Cappella_Sistina'
  },
  {
    id: 44,
    titolo: 'Sacco di Prato',
    data: '29 agosto 1512',
    anno: 1512,
    luogo: 'Prato',
    categoria: 'Rinascimento',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Targa_commemorativa_del_Sacco_di_Prato.jpg/330px-Targa_commemorativa_del_Sacco_di_Prato.jpg',
    lat: 43.8777,
    lon: 11.1023,
    descrizione: "L'esercito spagnolo guidato da Raimondo de Cardona saccheggia Prato, aprendo la strada al ritorno dei Medici al potere a Firenze.",
    fonte: 'https://it.wikipedia.org/wiki/Sacco_di_Prato'
  },
  {
    id: 45,
    titolo: 'Peste del 1630 a Milano',
    data: '1629-1633 (massima diffusione nel 1630)',
    anno: 1630,
    luogo: 'Milano',
    categoria: 'Età moderna',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Melchiorre_Gherardini%2C_Piazza_di_S._Babila_durante_la_peste_del_1630.jpg/330px-Melchiorre_Gherardini%2C_Piazza_di_S._Babila_durante_la_peste_del_1630.jpg',
    lat: 45.4776,
    lon: 9.2050,
    descrizione: 'Un\'epidemia di peste bubbonica colpisce il nord Italia, con Milano tra le città più duramente segnate.',
    fonte: 'https://it.wikipedia.org/wiki/Peste_del_1630',
    curiosita: "È ricordata anche come \"peste manzoniana\", perché Alessandro Manzoni la raccontò ne \"I promessi sposi\"."
  },
  {
    id: 46,
    titolo: "Eruzione dell'Etna del 1669",
    data: '8 marzo - 11 luglio 1669',
    anno: 1669,
    luogo: 'Catania',
    categoria: 'Età moderna',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Etna_eruzione_1669_platania.jpg/330px-Etna_eruzione_1669_platania.jpg',
    lat: 37.5079,
    lon: 15.0830,
    descrizione: "Una violenta eruzione dell'Etna produce colate laviche che raggiungono e distruggono in parte i quartieri occidentali di Catania.",
    fonte: "https://it.wikipedia.org/wiki/Eruzione_dell'Etna_del_1669",
    curiosita: "La lava raggiunse i quartieri occidentali di Catania e continuò ad avanzare fino a sfociare in mare l'11 luglio."
  },
  {
    id: 47,
    titolo: 'Terremoto del Val di Noto',
    data: '9-11 gennaio 1693',
    anno: 1693,
    luogo: 'Noto',
    categoria: 'Età moderna',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Mappa_Terremoto_Val_di_Noto_1693.png/330px-Mappa_Terremoto_Val_di_Noto_1693.png',
    lat: 36.8917,
    lon: 15.0704,
    descrizione: 'Un fortissimo terremoto devasta la Sicilia sud-orientale, distruggendo quasi completamente Noto e altre città della zona.',
    fonte: 'https://it.wikipedia.org/wiki/Terremoto_del_Val_di_Noto_del_1693',
    curiosita: 'Con una magnitudo stimata di 7,3, è considerato uno dei terremoti più forti mai avvenuti in Italia.'
  },
  {
    id: 48,
    titolo: 'Battaglia di Calatafimi',
    data: '15 maggio 1860',
    anno: 1860,
    luogo: 'Calatafimi, Trapani',
    categoria: 'Risorgimento',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Battle_of_Calatafimi.jpg/500px-Battle_of_Calatafimi.jpg',
    lat: 37.9186,
    lon: 12.8695,
    descrizione: 'Garibaldi e i suoi volontari sconfiggono le truppe borboniche a Calatafimi, nella prima vittoria della spedizione dei Mille in Sicilia.',
    fonte: 'https://it.wikipedia.org/wiki/Battaglia_di_Calatafimi'
  },
  {
    id: 49,
    titolo: 'Rivolta della Gancia',
    data: '4 aprile 1860',
    anno: 1860,
    luogo: 'Convento della Gancia, Palermo',
    categoria: 'Risorgimento',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Assalto_al_Convento_della_Gancia_di_Palermo_4_aprile_1860_-_ISSG_1860_pag._196.JPG/330px-Assalto_al_Convento_della_Gancia_di_Palermo_4_aprile_1860_-_ISSG_1860_pag._196.JPG',
    lat: 38.1146,
    lon: 13.3636,
    descrizione: 'Un gruppo di rivoltosi occupa il convento della Gancia a Palermo, dando avvio a un\'insurrezione che anticipa di settimane l\'arrivo di Garibaldi in Sicilia.',
    fonte: 'https://it.wikipedia.org/wiki/Rivolta_della_Gancia',
    curiosita: "I Borbonici soffocarono rapidamente la rivolta, ma il suo ricordo contribuì a preparare la successiva presa di Palermo da parte di Garibaldi, il 27 maggio."
  },
  {
    id: 50,
    titolo: 'Battaglia del Volturno',
    data: '26 settembre - 2 ottobre 1860',
    anno: 1860,
    luogo: 'Santa Maria Capua Vetere, Caserta',
    categoria: 'Risorgimento',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Mille_a_Capua_Vizzotto2.JPG/330px-Mille_a_Capua_Vizzotto2.JPG',
    lat: 41.0808,
    lon: 14.2447,
    descrizione: "Lungo il fiume Volturno, l'esercito di Garibaldi respinge il tentativo borbonico di riconquistare Napoli.",
    fonte: 'https://it.wikipedia.org/wiki/Battaglia_del_Volturno'
  },
  {
    id: 51,
    titolo: "Terremoto dell'Irpinia",
    data: '23 novembre 1980',
    anno: 1980,
    luogo: 'Castelnuovo di Conza, Avellino',
    categoria: 'Novecento',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/19801123_183453_irpinia_quake_intensity.jpg/330px-19801123_183453_irpinia_quake_intensity.jpg',
    lat: 40.8159,
    lon: 15.3115,
    descrizione: "Un violento terremoto colpisce l'Irpinia, provocando migliaia di vittime e devastando decine di comuni tra Campania e Basilicata.",
    fonte: "https://it.wikipedia.org/wiki/Terremoto_dell'Irpinia_del_1980"
  },
  {
    id: 52,
    titolo: 'Strage di Bologna',
    data: '2 agosto 1980',
    anno: 1980,
    luogo: 'Stazione di Bologna Centrale',
    categoria: 'Novecento',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Stragedibologna-2.jpg/330px-Stragedibologna-2.jpg',
    lat: 44.5054,
    lon: 11.3426,
    descrizione: "Una bomba esplode nella sala d'aspetto della stazione di Bologna, in uno degli attentati più gravi della storia repubblicana italiana.",
    fonte: 'https://it.wikipedia.org/wiki/Strage_di_Bologna',
    curiosita: "L'esplosione, alle 10:25 del mattino, provocò 85 morti e oltre 200 feriti."
  },
  {
    id: 53,
    titolo: 'Alluvione del Polesine',
    data: '14 novembre 1951',
    anno: 1951,
    luogo: 'Occhiobello, Rovigo',
    categoria: 'Novecento',
    lat: 44.9317,
    lon: 11.6144,
    descrizione: 'La rottura degli argini del Po allaga gran parte del Polesine, costringendo decine di migliaia di persone ad abbandonare le proprie case.',
    fonte: 'https://it.wikipedia.org/wiki/Alluvione_del_Polesine_del_1951',
    curiosita: "L'argine maestro del Po si ruppe in più punti nella stessa serata: alle 19:45, poi alle 20:00 e alle 20:15 del 14 novembre."
  },
  {
    id: 54,
    titolo: 'Arrivo della Peste Nera a Messina',
    data: 'Fine settembre 1347',
    anno: 1347,
    luogo: 'Porto di Messina',
    categoria: 'Medioevo',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Trionfo_della_morte%2C_gi%C3%A0_a_palazzo_sclafani%2C_galleria_regionale_di_Palazzo_Abbatellis%2C_palermo_%281446%29_%2C_affresco_staccato.jpg/330px-Trionfo_della_morte%2C_gi%C3%A0_a_palazzo_sclafani%2C_galleria_regionale_di_Palazzo_Abbatellis%2C_palermo_%281446%29_%2C_affresco_staccato.jpg',
    lat: 38.1938,
    lon: 15.5540,
    descrizione: "Una nave genovese proveniente da Caffa, in Crimea, attracca al porto di Messina portando con sé la peste: da qui il contagio si diffonde rapidamente in Sicilia e poi nel resto d'Europa.",
    fonte: 'https://it.wikipedia.org/wiki/Peste_nera',
    curiosita: "Papa Clemente VI si salvò forse per caso: durante l'epidemia restò rinchiuso ad Avignone tra due grandi falò sempre accesi, il cui calore teneva lontane le pulci che trasmettevano il contagio."
  },
  {
    id: 55,
    titolo: 'Caduta della Repubblica di Venezia',
    data: '12 maggio 1797',
    anno: 1797,
    luogo: 'Palazzo Ducale, Venezia',
    categoria: 'Età moderna',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Manin%27s_abdication.jpg/330px-Manin%27s_abdication.jpg',
    lat: 45.4341,
    lon: 12.3404,
    descrizione: 'Il Maggior Consiglio, riunito per l\'ultima volta con soli 537 patrizi sui 1200 aventi diritto, dichiara decaduta la Repubblica dopo oltre mille anni: il doge Ludovico Manin depone le insegne del potere.',
    fonte: 'https://it.wikipedia.org/wiki/Caduta_della_Repubblica_di_Venezia',
    curiosita: 'Contrariamente ai timori dei nobili, il popolo accolse la notizia gridando "viva san Marco!" e issando il gonfalone marciano in piazza, arrivando persino a tentare di reinsediare il doge.'
  },
  {
    id: 56,
    titolo: 'Proclamazione della Repubblica Napoletana',
    data: '23 gennaio 1799',
    anno: 1799,
    luogo: 'Napoli',
    categoria: 'Età moderna',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/ParthenopR.png/330px-ParthenopR.png',
    lat: 40.8518,
    lon: 14.2681,
    descrizione: 'Il generale francese Jean Étienne Championnet proclama a Napoli la Repubblica Napoletana; priva di largo consenso popolare, durerà appena cinque mesi.',
    fonte: 'https://it.wikipedia.org/wiki/Repubblica_Napoletana_(1799)',
    curiosita: "La Repubblica cadde il 22 giugno 1799 con la resa dell'ultimo baluardo, Castel Sant'Elmo, dopo che le truppe francesi si erano ritirate lasciando i repubblicani senza difesa."
  },
  {
    id: 57,
    titolo: 'Proclamazione della Repubblica Romana',
    data: '9 febbraio 1849',
    anno: 1849,
    luogo: 'Campidoglio, Roma',
    categoria: 'Risorgimento',
    lat: 41.8931,
    lon: 12.4828,
    descrizione: "L'assemblea costituente proclama la Repubblica Romana sul Campidoglio, introducendo il suffragio universale maschile e abolendo la pena di morte.",
    fonte: 'https://it.wikipedia.org/wiki/Repubblica_Romana_(1849)',
    curiosita: 'La giornalista americana Margaret Fuller assistette di persona alla proclamazione, raccontandola ai lettori del New York Daily Tribune.'
  },
  {
    id: 58,
    titolo: 'Marcia su Roma',
    data: '27-31 ottobre 1922',
    anno: 1922,
    luogo: 'Roma',
    categoria: 'Novecento',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/March_on_Rome_1922_-_Alle_porte_di_Roma.png/330px-March_on_Rome_1922_-_Alle_porte_di_Roma.png',
    lat: 41.8955,
    lon: 12.4823,
    descrizione: "Migliaia di squadristi fascisti marciano su Roma; il re Vittorio Emanuele III rifiuta di firmare lo stato d'assedio e il 30 ottobre incarica Mussolini di formare il governo.",
    fonte: 'https://it.wikipedia.org/wiki/Marcia_su_Roma',
    curiosita: "Il rifiuto del re di firmare il decreto di stato d'assedio tolse ogni ostacolo militare all'avanzata fascista, che poté così entrare a Roma senza scontri."
  },
  {
    id: 59,
    titolo: 'Delitto Matteotti',
    data: '10 giugno 1924',
    anno: 1924,
    luogo: 'Lungotevere Arnaldo da Brescia, Roma',
    categoria: 'Novecento',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Giacomo_Matteotti_2.jpg/330px-Giacomo_Matteotti_2.jpg',
    lat: 41.9130,
    lon: 12.4722,
    descrizione: 'Il deputato socialista Giacomo Matteotti viene rapito e ucciso da una squadra fascista lungo il Tevere, pochi giorni dopo aver denunciato in Parlamento i brogli delle elezioni.',
    fonte: 'https://it.wikipedia.org/wiki/Delitto_Matteotti',
    curiosita: 'Il corpo di Matteotti fu ritrovato solo il 16 agosto 1924, oltre due mesi dopo il rapimento, in una campagna vicino a Riano, circa 20 km a nord di Roma.'
  },
  {
    id: 60,
    titolo: 'Patti Lateranensi',
    data: '11 febbraio 1929',
    anno: 1929,
    luogo: 'Palazzo del Laterano, Roma',
    categoria: 'Novecento',
    lat: 41.8849,
    lon: 12.5037,
    descrizione: 'Il cardinale Pietro Gasparri e Benito Mussolini firmano nel Palazzo del Laterano i Patti che risolvono la questione romana, istituendo lo Stato della Città del Vaticano.',
    fonte: 'https://it.wikipedia.org/wiki/Patti_lateranensi',
    curiosita: '11 febbraio fu scelto anche per il suo valore simbolico: era il 71º anniversario della prima apparizione della Madonna di Lourdes.'
  },
  {
    id: 61,
    titolo: 'Sbarco alleato in Sicilia (Operazione Husky)',
    data: '10 luglio 1943',
    anno: 1943,
    luogo: 'Gela, Caltanissetta',
    categoria: 'Novecento',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/The_British_Army_in_Sicily_1943_NA4306.jpg/330px-The_British_Army_in_Sicily_1943_NA4306.jpg',
    lat: 37.0663,
    lon: 14.2478,
    descrizione: "Le forze alleate sbarcano in Sicilia in una delle più grandi operazioni anfibie della Seconda guerra mondiale: la 7ª Armata statunitense tocca terra a Gela, l'8ª Armata britannica più a est verso Siracusa.",
    fonte: 'https://it.wikipedia.org/wiki/Operazione_Husky',
    curiosita: 'Dopo il bombardamento di Pantelleria, che scaricò 6.000 tonnellate di esplosivo su un\'isola di appena 12x7 km, gli oltre 11.000 soldati della guarnigione si arresero senza sparare un colpo.'
  },
  {
    id: 62,
    titolo: 'Armistizio di Cassibile',
    data: '3 settembre 1943',
    anno: 1943,
    luogo: 'Cassibile, Siracusa',
    categoria: 'Novecento',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Armistice_1943_Castellano_Eisenhower.jpg/330px-Armistice_1943_Castellano_Eisenhower.jpg',
    lat: 37.0167,
    lon: 15.1667,
    descrizione: "Il generale Giuseppe Castellano firma per l'Italia, e Walter Bedell Smith per gli Alleati, l'armistizio che pone fine alle ostilità tra Italia e Alleati; sarà reso pubblico solo l'8 settembre.",
    fonte: 'https://it.wikipedia.org/wiki/Armistizio_di_Cassibile',
    curiosita: 'Il luogo esatto della firma, in un uliveto vicino Cassibile, rimase a lungo incerto: la lapide originale fu rubata nel 1955 e una lapide corretta fu posta solo nel 2016.'
  },
  {
    id: 63,
    titolo: 'Eccidio delle Fosse Ardeatine',
    data: '24 marzo 1944',
    anno: 1944,
    luogo: 'Cave Ardeatine, Roma',
    categoria: 'Novecento',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Roma-fosseardeatine6.jpg/330px-Roma-fosseardeatine6.jpg',
    lat: 41.8567,
    lon: 12.5103,
    descrizione: "Le truppe di occupazione tedesche uccidono 335 persone nelle cave Ardeatine, come rappresaglia per l'attentato partigiano di via Rasella del giorno precedente, in cui erano morti 33 soldati tedeschi.",
    fonte: 'https://it.wikipedia.org/wiki/Eccidio_delle_Fosse_Ardeatine',
    curiosita: 'Un mese dopo l\'eccidio, i partigiani di Bandiera Rossa disarmarono le guardie all\'ingresso delle cave ed esposero un cartello con la scritta "vi vendicheranno".'
  },
  {
    id: 64,
    titolo: 'Strage di Marzabotto',
    data: '29 settembre - 5 ottobre 1944',
    anno: 1944,
    luogo: 'Monte Sole, Marzabotto',
    categoria: 'Novecento',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Eccidio_monte_sole1.jpg/330px-Eccidio_monte_sole1.jpg',
    lat: 44.3417,
    lon: 11.2058,
    descrizione: 'Reparti delle SS comandati dal maggiore Walter Reder compiono una serie di stragi di civili sulle pendici di Monte Sole, nel comune di Marzabotto e nei comuni vicini.',
    fonte: 'https://it.wikipedia.org/wiki/Eccidio_di_Marzabotto',
    curiosita: "Nel 1994, per il cinquantesimo anniversario, il vicepresidente russo Aleksandr Rutskoy donò all'arcidiocesi di Bologna una campana fusa con materiali bellici, posta vicino alle rovine della chiesa di Casaglia."
  },
  {
    id: 65,
    titolo: 'Liberazione di Roma',
    data: '4 giugno 1944',
    anno: 1944,
    luogo: 'Colosseo, Roma',
    categoria: 'Novecento',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/TD_al_Colosseo_1944.jpg/330px-TD_al_Colosseo_1944.jpg',
    lat: 41.8902,
    lon: 12.4922,
    descrizione: 'Le truppe alleate, guidate dal generale Mark Clark, entrano a Roma senza incontrare resistenza: i tedeschi si erano ritirati verso nord per evitare combattimenti nella capitale.',
    fonte: 'https://it.wikipedia.org/wiki/Liberazione_di_Roma',
    curiosita: 'Il giorno dopo la liberazione, il presidente Roosevelt parlò alla radio agli americani celebrando il valore simbolico di Roma, ma ricordando che la guerra contro la Germania era ancora lunga.'
  },
  {
    id: 66,
    titolo: 'Agguato di via Fani e rapimento di Aldo Moro',
    data: '16 marzo 1978',
    anno: 1978,
    luogo: 'Via Mario Fani, Roma',
    categoria: 'Novecento',
    lat: 41.8943,
    lon: 12.4785,
    descrizione: "Un commando delle Brigate Rosse tende un agguato all'auto di Aldo Moro all'incrocio tra via Fani e via Stresa, uccidendo i cinque uomini della scorta e rapendo lo statista, che sarà ucciso 55 giorni dopo.",
    fonte: 'https://it.wikipedia.org/wiki/Rapimento_di_Aldo_Moro',
    curiosita: 'Uno degli agenti di scorta, Francesco Zizzi, fu l\'unico a non morire sul colpo: portato in ospedale ancora vivo, morì solo alcune ore dopo.'
  },
  {
    id: 67,
    titolo: 'Terremoto del Friuli',
    data: '6 maggio 1976',
    anno: 1976,
    luogo: 'Tarcento, Udine',
    categoria: 'Novecento',
    lat: 46.2620,
    lon: 13.2990,
    descrizione: "Un terremoto di magnitudo 6,5 colpisce il Friuli, con epicentro vicino Tarcento, causando quasi mille vittime e lasciando senza casa oltre 100.000 persone.",
    fonte: 'https://it.wikipedia.org/wiki/Terremoto_del_Friuli_del_1976',
    curiosita: 'Gli abitanti lo chiamarono "Orcolat" (l\'orco, in friulano); la rapida ricostruzione che seguì è ancora oggi citata come modello, noto come "Modello Friuli".'
  },
  {
    id: 68,
    titolo: 'Strage di Capaci',
    data: '23 maggio 1992',
    anno: 1992,
    luogo: 'Autostrada A29, Capaci',
    categoria: 'Novecento',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Strage_di_capaci.jpg/330px-Strage_di_capaci.jpg',
    lat: 38.1828,
    lon: 13.2447,
    descrizione: "Un'esplosione di circa 300 kg di tritolo, fatta brillare sotto l'autostrada A29 nei pressi di Capaci, uccide il giudice Giovanni Falcone, la moglie Francesca Morvillo e i tre agenti di scorta.",
    fonte: 'https://it.wikipedia.org/wiki/Strage_di_Capaci',
    curiosita: "Pochi istanti prima dell'esplosione Falcone si voltò per prendere le chiavi dell'auto: quell'attimo di rallentamento modificò di poco la posizione della vettura rispetto al momento previsto per l'innesco."
  },
  {
    id: 69,
    titolo: "Strage di via D'Amelio",
    data: '19 luglio 1992',
    anno: 1992,
    luogo: "Via D'Amelio, Palermo",
    categoria: 'Novecento',
    lat: 38.1431,
    lon: 13.3547,
    descrizione: "Un'autobomba con circa 90 kg di esplosivo uccide in via D'Amelio a Palermo il giudice Paolo Borsellino e i cinque agenti della sua scorta, appena 57 giorni dopo la strage di Capaci.",
    fonte: "https://it.wikipedia.org/wiki/Strage_di_via_D%27Amelio",
    curiosita: 'Emanuela Loi, una delle agenti di scorta uccise, fu la prima donna della Polizia di Stato a morire in servizio.'
  },
  {
    id: 70,
    titolo: "Terremoto dell'Aquila",
    data: '6 aprile 2009',
    anno: 2009,
    luogo: "L'Aquila",
    categoria: 'Novecento',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/L%27Aquila_eathquake_prefettura.jpg/330px-L%27Aquila_eathquake_prefettura.jpg',
    lat: 42.3420,
    lon: 13.3800,
    descrizione: "Un terremoto di magnitudo 6,3 colpisce L'Aquila e i comuni vicini alle 3:32 di notte, causando 308 vittime e devastando il centro storico della città.",
    fonte: "https://it.wikipedia.org/wiki/Terremoto_dell%27Aquila_del_2009",
    curiosita: "Tra i sopravvissuti estratti dalle macerie c'era una donna di 98 anni che raccontò di aver passato il tempo lavorando all'uncinetto mentre era intrappolata."
  },
  {
    id: 71,
    titolo: 'Crollo del ponte Morandi',
    data: '14 agosto 2018',
    anno: 2018,
    luogo: 'Genova',
    categoria: 'Novecento',
    immagine: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Ponte_Morandi_Genova_Campi_014.jpg/330px-Ponte_Morandi_Genova_Campi_014.jpg',
    lat: 44.4258,
    lon: 8.8889,
    descrizione: 'Una campata di circa 250 metri del ponte Morandi, sul torrente Polcevera, crolla improvvisamente insieme al pilone numero 9, causando 43 vittime.',
    fonte: 'https://it.wikipedia.org/wiki/Crollo_del_viadotto_Polcevera',
    curiosita: 'Le indagini rivelarono che, dei 464 cavi del pilone crollato, solo 4 (meno dell\'1%) risultavano privi di segni di corrosione.'
  }
];

export default eventi;
